server:
  port: 8078
upstream:
  order:
    serviceAddr: ${ORDER_SERVICE_HOST}
    servicePort: 8080

spring:
  application:
    name: ${SERVICE_NAME}
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: tmax-test
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer : org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

opentracing:
  jaeger:
    udp-sender:
      host: ${JAEGER_AGENT_HOST_ADDR}
      port: 6831
    log-spans: true
